fn main() {
	std::env::set_var("CC", "clang");

	let files = vec![
		"ball.c",
		"block.c",
		"bubble.c",
		"dot.c",
		"elements.c",
		"font.c",
		"input.c",
		"main.c",
		"menu-input.c",
		"menu.c",
		"object.c",
		"random.c",
		"reset.c",
		"save.c",
		"vector.c",
		"wheel-frames.c",
		"wheel.c",
		"render/ball.c",
		"render/bg.c",
		"render/bg.c",
		"render/ball.c",
		"render/bg.c",
		"render/bubble.c",
		"render/dot.c",
		"render/draw.c",
		"render/menu.c",
		"render/object.c",
		"render/scale.c",
		"render/wheel.c",
	];

	cc::Build::new()
		.warnings(false)
		.files(files)
		.compile("pg1.exe");
	
	cargo_emit::rerun_if_changed!(
		"ball.c",
		"block.c",
		"bubble.c",
		"dot.c",
		"elements.c",
		"font.c",
		"input.c",
		"main.c",
		"menu-input.c",
		"menu.c",
		"object.c",
		"random.c",
		"reset.c",
		"save.c",
		"vector.c",
		"wheel-frames.c",
		"wheel.c",
		"render/ball.c",
		"render/bg.c",
		"render/bg.c",
		"render/ball.c",
		"render/bg.c",
		"render/bubble.c",
		"render/dot.c",
		"render/draw.c",
		"render/menu.c",
		"render/object.c",
		"render/scale.c",
		"render/wheel.c",
	);
}
